import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../_components/Navbar";
import ReduxWrapper from "@/provider/redux/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trade App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <div className="pt-20">{children}</div>
        </body>
      </html>
    </ReduxWrapper>
  );
}
